#!/usr/bin/env python3

# This is a small script intended to convert a zip dump of the OcTranspo
# schedule data (from http://data.ottawa.ca/dataset/oc-transpo-schedules) to a
# sqlite database

import sys
import os
import zipfile
import csv
import io
import sqlalchemy
from sqlalchemy.orm import sessionmaker

from orm import *

zip_filename, sqlite_filename = sys.argv[1:]

# Set up the DB
if os.path.exists(sqlite_filename):
    os.remove(sqlite_filename)
engine = sqlalchemy.create_engine('sqlite:///' + sqlite_filename)
Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)
session = Session()

class InsertAs(object):
    def __init__(self, type_):
        self._type = type_

    def __call__(self, row, session):
        session.add(self._type(**row))

csv_handlers = [
        ("stops.txt", InsertAs(Stop)),
        ("routes.txt", InsertAs(Route)),
        ("trips.txt", InsertAs(Trip)),
        ("stop_times.txt", InsertAs(StopTime)),
        ]

with zipfile.ZipFile(zip_filename) as zip_file:
    for csv_filename, handler in csv_handlers:
        sys.stderr.write("Handling "+csv_filename)
        sys.stderr.flush()
        with zip_file.open(csv_filename) as csv_file:
            csv_stream = io.TextIOWrapper(csv_file, encoding='utf-8', newline='')
            numRows = 0
            for row in csv.DictReader(csv_stream):
                handler(row, session)
                numRows += 1
                if numRows >= 10000:
                    sys.stderr.write(".")
                    sys.stderr.flush()
                    numRows = 0
                    session.commit()
            sys.stderr.write(".")
            sys.stderr.flush()
            session.commit()
        sys.stderr.write("\n")
        sys.stderr.flush()

